stableVersion: 3.3.3
developmentVersion: 3.x.x-SNAPSHOT
jdkJavadocsBase: https://docs.oracle.com/javase/8/docs/api
profiles:
  development:
  production:
    base_url: https://www.togglz.org/
    google_analytics:
      account: UA-7295879-8
